### ISSUE TITLE
[Documentation] Which Symfony app/console commands need to be documented?

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender-documentation#79]
For the interested user?

Like:

* cache:clear? As an alternative to rm -rf app/cache/*

* server:run: is described but can be further listet
* server:start
* server:status
* server:stop

http://doc.mapbender.org/de/book/installation/configuration.html

With a little help from @eSlider @LazerTiberius @werrolf @swinkelmann

**Comment by fhaefker** [comment]
Dear @CharlyUnicorn

Please create a pull request according to your recommendations.

**Comment by rschwammborn** [comment]
Hey, it seems to me that documenting those features improved working with bash commands in Mapbender. In my opinion, the cache possibilities are documented just alright now. For more information on the topic, advanced users could always use `app/console cache:clear --help`. Because all talked about issues are implemented in the documentation one way or the other and there are topic intersections with issue #91 , I'm closing both issues now. Thanks again for your work, y'all!
