### ISSUE TITLE
Add documentation for app/console-command about user-creation (mapbender:user:create)

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#91]
* from 3.0.8.1 you can create/change users with password (not only root)
* think about a general page to document app/console commands

```
app/console mapbender:user:create --help
Usage:
  mapbender:user:create [options] [--] <name>

Arguments:
  name

Options:
      --update             Allow update of existing user
      --password=PASSWORD
      --email=EMAIL
```

**Comment by astroidex** [comment]
Lilian is currently working at this ticket

**Comment by astroidex** [comment]
The new documentation looks very good. Thanks a lot.

Please add information about the following commands
- app/console doctrine:schema:update --dump-sql
- app/console doctrine:schema:update --force
- app/console assets:install web --symlink --relative

**Comment by lbromen** [comment]
maybe the command doctrine:schema:update (with -dump-sql and -force) is depricated and can be replaced by app/console doctrine:schema:validate and app/console mapbender:database:upgrade?

**Comment by rschwammborn** [comment]
Hey, it seems to me that documenting those features improved working with bash commands in Mapbender. Because all talked about issues are implemented in the documentation one way or the other and there are topic intersections with issue #79 , I'm closing both issues now. Thanks again for your work, y'all!
